FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake llvm-dev libclang-14-dev clang git

COPY . /repo
WORKDIR /repo/build
RUN cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/install
RUN make -j8
RUN make install

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y llvm-dev libclang-14-dev
COPY --from=builder /install /install
